### ISSUE TITLE
Just not working

### ISSUE THREAD

**Issue by DigiAngel** [bro/packages#47]
So I've been mucking with bro-pkg for a bit and I just can't get it to work.  I'll start with how I compile bro:
~~~
./configure --prefix=/opt/bro --with-pcap=/opt/pfring
~~~

next up I symlink bro, bro-ctl, and bro-config from /opt/bro/bin/:
~~~
lrwxrwxrwx 1 root root    16 Mar 10  2017 bro -> /opt/bro/bin/bro
lrwxrwxrwx 1 root root    23 Feb 14 22:08 bro-config -> /opt/bro/bin/bro-config
lrwxrwxrwx 1 root root    19 Mar 10  2017 broctl -> /opt/bro/bin/broctl
~~~

next, configure bro-pkg with sudo bro-pkg autoconfig which gives me, in my user dir:
~~~
[sources]
bro = https://github.com/bro/packages

[paths]
state_dir = /home/<user>/.bro-pkg
script_dir = /opt/bro/share/bro/site
plugin_dir = /opt/bro/lib/bro/plugins
bro_dist = /home/<user>/build/bro-2.5.3
~~~

which looks accurate.  In trying to install intel-seen-more I get:
~~~
The following packages will be INSTALLED:
  bro/j-gras/intel-seen-more (0.2.0)

The following dependencies will be INSTALLED:
  bro/sethhall/domain-tld (master) (suggested)

Proceed? [Y/n] Y
Installing "bro/j-gras/intel-seen-more"
Failed installing "bro/j-gras/intel-seen-more": no __load__.bro file found in package's 'script_dir' : scripts
Installing "bro/sethhall/domain-tld"
Installed "bro/sethhall/domain-tld" (master)
Loaded "bro/sethhall/domain-tld"
~~~

I then add @packages to my local.bro.  After running a test I get:
~~~
fatal error in /opt/bro/share/bro/site/local.bro, line 130: can't find packages
~~~

Am I missing something blatant?  Thank you.

**Comment by jsiwek** [comment]
First, it's not clear what users are actually involved here.  Whose ~/.bro-pkg/config file is that?  Are you running `bro-pkg install` as the same user that ran `bro-pkg autoconfig` ?  If not, that's likely the problem -- I'm guessing the "can't find packages" error is because stuff actually got installed to ~/.bro-pkg/script_dir/packages of the user that performed `bro-pkg install`.

Second, the 'intel-seen-more' package doesn't actually get installed, since the package's metadata may be incorrect.  You should show that error to the packager of that specific package for help: https://github.com/J-Gras/intel-seen-more

**Comment by DigiAngel** [comment]
That's the user that runs the command...as sudo.  Yes, same user ran the autoconfig command.  Where is the packages directory supposed to end up in?  And I'll let the other person know about the error.  Thank you.

**Comment by DigiAngel** [comment]
Ok intel-seen-more is fixed:  https://github.com/J-Gras/intel-seen-more/issues/1

**Comment by DigiAngel** [comment]
Ok so after more digging the tl;dr is "don't run bro-pkg non-root if your install was installed as root/sudo".   Gleaned info here:
~~~
bro-pkg list
OSError: [Errno 13] Permission denied: '/opt/bro/share/bro/site/packages'
error: user does not have write access in /opt/bro/share/bro/site
error: user does not have write access in /opt/bro/lib/bro/plugins

sudo bro-pkg list
bro/j-gras/intel-seen-more (installed: 0.2.1) - Additional seen-triggers for Bro's intelligence framework.
bro/sethhall/domain-tld (installed: master) - A library for getting the "effective tld" of a domain name.
~~~

of interest, bro was installed with sudo make install and I can do a "sudo touch bleh" within the site dir at it works fine, but bro-pkg didn't create the packages dir within the site dir with run as sudo.  Quick fix was to run bro-pkg autoconfig and installs as root, not sudo.
